version: '3.8'
services:
  nestjs-api:
    stdin_open: true
    container_name: nestjs-api
    image: node:latest
    working_dir: /usr/src/app
    command: '/usr/src/app/docker/docker-run-dev.sh'
    env_file:
      - ../.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    restart: always
    volumes:
      - ..:/usr/src/app
      - ../node_modules:/usr/src/app/node_modules

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=houstonAdmin
      - POSTGRES_PASSWORD=houstonAdmin
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - '5555:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: houstonAdmin@example.com
      PGADMIN_DEFAULT_PASSWORD: houstonAdmin
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
